name: Python Package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest pytest-asyncio black isort mypy
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install -e .
    - name: Lint with black
      run: |
        black --check evrmore_rpc tests examples
    - name: Check imports with isort
      run: |
        isort --check-only --profile black evrmore_rpc tests examples
    - name: Type check with mypy
      run: |
        mypy evrmore_rpc
    - name: Test with pytest
      run: |
        pytest
    - name: Check publication readiness
      run: |
        python scripts/check_publication.py 